// <auto-generated />
using System;
using EMSuiteVisualConfigurator.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMSuiteVisualConfigurator.Data.Migrations
{
    [DbContext(typeof(EMSuiteVisualConfiguratorDbContext))]
    [Migration("20221205142428_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("EntitySequence");

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [EntitySequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.AccessPoint", b =>
                {
                    b.HasBaseType("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("bit");

                    b.ToTable("accessPoints");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Channel", b =>
                {
                    b.HasBaseType("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("bit");

                    b.Property<int?>("PortId")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasIndex("PortId");

                    b.HasIndex("ZoneId");

                    b.ToTable("channels");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.EMSuiteConfiguration", b =>
                {
                    b.HasBaseType("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity");

                    b.ToTable("emsuiteConfigurations");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Logger", b =>
                {
                    b.HasBaseType("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity");

                    b.Property<int?>("AccessPointId")
                        .HasColumnType("int");

                    b.Property<int>("Battery")
                        .HasColumnType("int");

                    b.Property<int>("SignalStrength")
                        .HasColumnType("int");

                    b.HasIndex("AccessPointId");

                    b.ToTable("loggers");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Port", b =>
                {
                    b.HasBaseType("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoggerId")
                        .HasColumnType("int");

                    b.Property<int>("SensorSerialNumber")
                        .HasColumnType("int");

                    b.HasIndex("LoggerId");

                    b.ToTable("ports");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Site", b =>
                {
                    b.HasBaseType("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EMSuiteConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EMSuiteConfigurationId");

                    b.ToTable("sites");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Zone", b =>
                {
                    b.HasBaseType("EMSuiteVisualConfigurator.CoreBusiness.Primitives.Entity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.HasIndex("SiteId");

                    b.ToTable("zones");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Channel", b =>
                {
                    b.HasOne("EMSuiteVisualConfigurator.CoreBusiness.Entities.Port", null)
                        .WithMany("Channels")
                        .HasForeignKey("PortId");

                    b.HasOne("EMSuiteVisualConfigurator.CoreBusiness.Entities.Zone", null)
                        .WithMany("Channels")
                        .HasForeignKey("ZoneId");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Logger", b =>
                {
                    b.HasOne("EMSuiteVisualConfigurator.CoreBusiness.Entities.AccessPoint", null)
                        .WithMany("Loggers")
                        .HasForeignKey("AccessPointId");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Port", b =>
                {
                    b.HasOne("EMSuiteVisualConfigurator.CoreBusiness.Entities.Logger", null)
                        .WithMany("Ports")
                        .HasForeignKey("LoggerId");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Site", b =>
                {
                    b.HasOne("EMSuiteVisualConfigurator.CoreBusiness.Entities.EMSuiteConfiguration", null)
                        .WithMany("Sites")
                        .HasForeignKey("EMSuiteConfigurationId");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Zone", b =>
                {
                    b.HasOne("EMSuiteVisualConfigurator.CoreBusiness.Entities.Site", null)
                        .WithMany("Zones")
                        .HasForeignKey("SiteId");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.AccessPoint", b =>
                {
                    b.Navigation("Loggers");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.EMSuiteConfiguration", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Logger", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Port", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Site", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("EMSuiteVisualConfigurator.CoreBusiness.Entities.Zone", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
